name: CustomItems
version: '${version}'
main: com.ulxsth.customitems.CustomItemsPlugin
api-version: '1.19'
commands:
  cgive:
    description: "カスタムアイテムを与えるよ"
    usage: "/cgive <item> [amount] [player]"
    permission: customitems.cgive

permissions:
    customitems.cgive:
        description: "カスタムアイテムを与えることができるよ"
        default: op